version: '3.8'
services:
  python3:
    build: .
    container_name: 'ds_default'
    working_dir: '/root/'
    tty: true
    command:
      jupyter-lab --ip=0.0.0.0 --allow-root --ServerApp.open_browser=False
    ports:
      - "8888:8888"
    volumes:
      - ./opt:/root/opt
      - ./root_jupyter:/root/.jupyter
